---
title: "R Notebook"
output: html_notebook
---

# misc observations - the first column being very wide is starting to annoy me! - how do we change the width of columns?

```{r}
# loading data - this time I've added the data to the same project folder but I did also try doing by direction to the file location
books_data <- read.csv("data/books.csv")

library(tidyverse)
library(skimr)
skim(books_data) # need to check this but looks like there are 6 character columns and 7 numeric.  Says no Group variables, not sure what this means.
```

```{r}
# In this section I'm going to check various meta data
nrow(books_data) # there are 11,123
ncol(books_data) # there are 13
dim(books_data) # returned the info I got above
names(books_data) # brings back the column headings - curious as to what the difference between "rowid" and "bookID" plus "isbn" and "isbn13"?  And what is "language_code" or "text_reviews_count"?  Do we need "rowID"? (remember how important it was in previous work).
head(books_data)
head(books_data, 10)
tail(books_data, 10)
glimpse(books_data)
view(books_data)

# I'll finish with this
str(books_data)
```

```{r}
# ok, lets see if we have any missing data
## this way seems quite laborious ie selecting each column individually to find if there's any missing data in that column
books_data %>% 
filter(is.na(publisher)) %>% 
  group_by(publisher) %>% 
  summarise(
    count = n ()
  ) %>% 
  arrange(count)
## interestingly this would suggest that there are no empyt fields - though I should have this checked that it actually works

```
```{r}
# here's an alternative, more efficient way
# again this seems to back up the finding that there no gaps in the data
books_data %>%
  summarise(count = sum(is.na(books_data)))
```

```{r}
### found this alternative online - I think this gives a more understandible view
sapply(books_data, function(x) sum(is.na(x)))

```

```{r}
# here I'm going to have a look at the publisher data
publishers_listed <- group_by(books_data, publisher)
summarise(publishers_listed, character_count = n()) %>% 
  arrange(publisher) 

# seems to be a lot of publishers with very similar names or upper vs lower case - are they typos etc? eg Abacus, Abacus Books and Abacus Books (London)
```

```{r}
# ok, ignoring the fact that there are problems with the entries in the publisher column, here is the weighting of publishers
books_data %>% 
  group_by(publisher) %>% 
summarise(
  count = n()
) %>% 
arrange(desc(count))
```

```{r}
# this section gives you the top 5 authors
books_data %>% 
  group_by(authors) %>% 
summarise(
  count = n()
) %>% 
arrange(desc(count)) %>% 
  head(5)
```

```{r}
# this section gives you the bottom 5
books_data %>% 
  group_by(authors) %>% 
summarise(
  count = n()
) %>% 
arrange(desc(count)) %>%
  tail(5)
```

```{r}
# summarising the data by language_code
books_data %>% 
  group_by(language_code) %>% 
  summarise(count = n()) %>% 
  arrange(desc(count))

# interesting to note that there are 4 categories for english: "eng", "en-US", "en-GB" and "en-CA"
```

```{r}
# attempt to merge the 4 english types together: english: "eng", "en-US", "en-GB" and "en-CA"
books_data_merged_eng_lang <- books_data %>%
  select(language_code) %>% 
  mutate(language_code = recode(language_code, "en-US" = "eng","en-GB" = "eng", "en-CA" = "eng"),
  group_by(language_code) %>% 
  summarise(count = n()) %>% 
  arrange(desc(count))       
         )

books_data_merged_eng_lang

books_data_merged_eng_lang %>% 
  group_by(language_code) %>% 
  summarise(count = n()) %>% 
  arrange(desc(count))
```

```{r}
# here should work out mean, median for? number of pages mean?

books_data_avg_pages <- books_data %>% 
  summarise(avg_pages = mean(num_pages))

books_data_avg_pages
```

```{r}
# summarising the data by number of pages
books_data %>% 
  group_by(num_pages) %>% 
  summarise(count = n()) %>% 
  arrange(desc(count))

```



```{r}
# code that I couldn't get to work so I should ask what's wrong - seems to be that mutate will only work on 1 (or 2) requests at any one time?)

books_data_merged_eng_lang <- books_data %>%
  group_by(language_code) %>% 
  mutate(
    language_code_merge_eng = if_else(language_code == "en-US", "eng", language_code),
    language_code_merge_eng = if_else(language_code == "en-GB", "eng", language_code), 
    language_code_merge_eng = if_else(language_code == "en-CA", "eng", language_code), .after = language_code) %>% 
  summarise(count = n()) %>% 
arrange(desc(count))

books_data_merged_eng_lang
```

```{r}
names(books_data)
```

