---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(janitor)
```

```{r}
# Q1

## reading in data
CardBase_data <- read_csv("data/CardBase.csv")
CustomerBase_data <- read_csv("data/CustomerBase.csv")
FraudBase_data <- read_csv("data/FraudBase.csv")
TransactionBase_data <- read_csv("data/TransactionBase.csv")

# cleaning column names
clean_names(CardBase_data)
clean_names(CustomerBase_data)
clean_names(FraudBase_data)
clean_names(TransactionBase_data)

# viewing the data
view(CardBase_data)
view(CustomerBase_data)
view(FraudBase_data)
view(TransactionBase_data)

# checking some meta data
glimpse(CardBase_data)
glimpse(CustomerBase_data)
glimpse(FraudBase_data)
glimpse(TransactionBase_data) 

# checking the column names in each of the files:
names(CardBase_data)
names(CustomerBase_data)
names(FraudBase_data)
names(TransactionBase_data)

```


```{r}
# Q2

cc_details_joined_to_customer_details <- inner_join(CardBase_data, CustomerBase_data, by = "Cust_ID")
cc_details_joined_to_customer_details %>% 
  summarise(across(.fns = ~ sum(is.na(.x))))

view(cc_details_joined_to_customer_details)
# however this only returns 500 rows and there are 5674 in the CustomerBase_data - therefore I'm going to switch to using the CustomerBase_data

cc_details_joined_to_customer_details <- right_join(CardBase_data, CustomerBase_data, by = "Cust_ID")
cc_details_joined_to_customer_details %>% 
  summarise(across(.fns = ~ sum(is.na(.x))))

```

```{r}
# Q3

names(TransactionBase_data)
names(FraudBase_data)
fraud_details_joined_to_transaction_details <- right_join(FraudBase_data, TransactionBase_data, by = c("Transaction_ID" = "Transaction_ID"))
fraud_details_joined_to_transaction_details %>% 
  summarise(across(.fns = ~ sum(is.na(.x))))
```
```{r}
# Q4
# this first version didn't work :-(
cc_details_joined_to_transaction_details <- left_join(CardBase_data, TransactionBase_data, by = c("Card_Number" =  "Credit_Card_ID"), na_matches = c("na", "never")) #%>% 
 # summarise(across(.fns = ~ sum(is.na(.x))))  
#  filter(is.na("Card_Number"))

cc_details_joined_to_transaction_details %>%
  summarise(across(.fns = ~ sum(is.na(.x))))

# finally figured it out
semi_join(CardBase_data, TransactionBase_data, by = c("Card_Number" =  "Credit_Card_ID"))





```

```{r}
#Q5 

library(tidyr)
hat_observations <- read_csv("data/hat_observations.csv")
# view(hat_observations)

hat_observations %>% 
separate(observation, c("hat_colour", 'hat_type'))
```

```{r}
# Q6

hat_observations_combined_date_formats <- hat_observations %>% 
  unite(date, c("day","month","year"), sep = "/")
hat_observations_combined_date_formats
```

```{r}
# 2 Extension

sparse_dataset <- left_join(cc_details_joined_to_customer_details, fraud_details_joined_to_transaction_details, by = c("Card_Number" =  "Credit_Card_ID"))

# I used this to work out with column had relevant missing data ie "Fraud_Flag"

sparse_dataset2 <- removing_na <- filter(sparse_dataset, !is.na(Fraud_Flag)) %>% 

sparse_dataset2


```
```{r}
# 2.2 tidyr

exam_scores <- read_csv("data/exam_scores.csv")
view(exam_scores)
```

